######################################################################
# Automatically generated by qmake (3.0) mar. nov. 11 10:08:47 2014
######################################################################

TEMPLATE = app
TARGET = Parser
INCLUDEPATH += .

# Input
HEADERS += IniParser.hpp ../Exceptions/Exception.hpp
SOURCES += IniParser.cpp main.cpp ../Exceptions/Exception.cpp
