######################################################################
# Automatically generated by qmake (3.0) mar. nov. 11 09:59:48 2014
######################################################################

TEMPLATE = app
TARGET = Exceptions
INCLUDEPATH += .

# Input
HEADERS += Exception.hpp
SOURCES += Exception.cpp
